server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /stream-proxy/ {
    proxy_pass http://127.0.0.1:3001/stream-proxy/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Cookie $http_cookie;
    proxy_buffering off;
  }

  location /api/ {
    proxy_pass http://127.0.0.1:3001/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Cookie $http_cookie;
    proxy_set_header Authorization $http_authorization;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
